// =============================================================================
// JsonLd Component — renders one or more JSON-LD schema objects as <script>
// -----------------------------------------------------------------------------
// Usage:
//   <JsonLd schema={organizationSchema()} />
//   <JsonLd schema={[organizationSchema(), websiteSchema()]} />
// =============================================================================

interface JsonLdProps {
  schema: object | object[];
}

/**
 * Renders JSON-LD <script> tags for structured data.
 * Server component — runs on the server for SEO crawlers.
 */
export function JsonLd({ schema }: JsonLdProps) {
  const schemas = Array.isArray(schema) ? schema : [schema];
  return (
    <>
      {schemas.map((s, i) => (
        <script
          key={i}
          type="application/ld+json"
          // Schema is generated by trusted code; no user input reaches here.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }}
        />
      ))}
    </>
  );
}
